### ISSUE TITLE
在激活软件everything(便携版, 非安装版)的窗口后,在该窗口上的任何鼠标点击和键盘输入操作, 都不会有日志打印,全局鼠标和键盘hook会失效啊

### ISSUE THREAD

**Issue by AfreyAwsome** [mahuifa/QtGlobalEvent#1]
在激活软件everything的窗口后,在该窗口上的任何鼠标点击和键盘输入操作, 都不会有日志打印,全局鼠标和键盘hook会失效啊

**Comment by mahuifa** [comment]
这种情况在我这里没有复现，启动everything后正常。

**Comment by AfreyAwsome** [comment]
> 这种情况在我这里没有复现，启动everything后正常。

我看了下, 我用的是官网的便携版, 不是安装版, 安装全局hook正常, 但是便携版就失效了
